### ISSUE TITLE
null\bin\winutils.exe error running on windows

### ISSUE THREAD

**Issue by Anupma97** [openzipkin/zipkin-dependencies#114]
Hi,

I am trying to run zipkin-dependencies-2.0.1.jar but I am getting below error.
18/09/13 21:46:02 ERROR Shell: Failed to locate the winutils binary in the hadoop binary path
java.io.IOException: Could not locate executable null\bin\winutils.exe in the Hadoop binaries.
at org.apache.hadoop.util.Shell.getQualifiedBinPath(Shell.java:378)
at org.apache.hadoop.util.Shell.getWinUtilsPath(Shell.java:393)
at org.apache.hadoop.util.Shell.(Shell.java:386)
at org.apache.hadoop.util.StringUtils.(StringUtils.java:79)
at org.apache.hadoop.security.Groups.parseStaticMapping(Groups.java:116)
at org.apache.hadoop.security.Groups.(Groups.java:93)
at org.apache.hadoop.security.Groups.(Groups.java:73)
at org.apache.hadoop.security.Groups.getUserToGroupsMappingService(Groups.java:293)
at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:283)
at org.apache.hadoop.security.UserGroupInformation.ensureInitialized(UserGroupInformation.java:260)
at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:789)
at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:774)
at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:647)
at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2467)
at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2467)
at scala.Option.getOrElse(Option.scala:121)
at org.apache.spark.util.Utils$.getCurrentUserName(Utils.scala:2467)
at org.apache.spark.SparkContext.(SparkContext.scala:292)
at zipkin2.dependencies.cassandra.CassandraDependenciesJob.run(CassandraDependenciesJob.java:163)
at zipkin2.dependencies.ZipkinDependenciesJob.main(ZipkinDependenciesJob.java:49)

You may check below link for complete issue background.
 https://github.com/openzipkin/zipkin/issues/2189

**Comment by adriancole** [comment]
the spark error is googlable but maybe someone has already setup this? cc @openzipkin/devops-tooling 

meanwhile are you able to use docker? that would eliminate the problem. Googling this says you'd need to install spark locally and using docker might be easier.

https://github.com/openzipkin/docker-zipkin-dependencies

**Comment by Anupma97** [comment]
> the spark error is googlable but maybe someone has already setup this? cc @openzipkin/devops-tooling
> 
> meanwhile are you able to use docker? that would eliminate the problem. Googling this says you'd need to install spark locally and using docker might be easier.
> 
> https://github.com/openzipkin/docker-zipkin-dependencies

I will try with docker.

**Comment by jorgheymans** [comment]
Spark on Windows seems to be a road paved with pain https://issues.apache.org/jira/browse/SPARK-2356 but it's not entirely our problem space. We could consider dedicating a section in `README.md` if this ever becomes a popular install target. Until then, closing.
