### ISSUE TITLE
update to Spark 3.0 and JDK 11 

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin-dependencies#119]
We can't move to JDK 11 until the following is sorted https://issues.apache.org/jira/browse/SPARK-24421

**Comment by shakuzen** [comment]
Just an update: it looks like that ticket has been resolved with fix version 3.0.0, which is not yet released.

**Comment by jorgheymans** [comment]
Note that currently running this on JDK11 i get below exception. Just thought i'd add it here because it seems unrelated to  https://issues.apache.org/jira/browse/SPARK-24421

```
19/08/20 15:49:36 WARN Resource: Detected type name in resource [zipkin:span-2019-08-20/span]. Type names are deprecated and will be removed in a later release.
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported class file major version 55
        at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:166)
        at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:148)
        at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:136)
        at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:237)
        at org.apache.spark.util.ClosureCleaner$.getClassReader(ClosureCleaner.scala:49)
        at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:517)
        at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:500)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
        at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:134)
        at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:134)
        at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:236)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
        at scala.collection.mutable.HashMap$$anon$1.foreach(HashMap.scala:134)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
        at org.apache.spark.util.FieldAccessFinder$$anon$3.visitMethodInsn(ClosureCleaner.scala:500)
        at org.apache.xbean.asm6.ClassReader.readCode(ClassReader.java:2175)
        at org.apache.xbean.asm6.ClassReader.readMethod(ClassReader.java:1238)
        at org.apache.xbean.asm6.ClassReader.accept(ClassReader.java:631)
        at org.apache.xbean.asm6.ClassReader.accept(ClassReader.java:355)
        at org.apache.spark.util.ClosureCleaner$$anonfun$org$apache$spark$util$ClosureCleaner$$clean$14.apply(ClosureCleaner.scala:307)
        at org.apache.spark.util.ClosureCleaner$$anonfun$org$apache$spark$util$ClosureCleaner$$clean$14.apply(ClosureCleaner.scala:306)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:306)
        at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:162)
        at org.apache.spark.SparkContext.clean(SparkContext.scala:2326)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$combineByKeyWithClassTag$1.apply(PairRDDFunctions.scala:88)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$combineByKeyWithClassTag$1.apply(PairRDDFunctions.scala:77)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
        at org.apache.spark.rdd.PairRDDFunctions.combineByKeyWithClassTag(PairRDDFunctions.scala:77)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$groupByKey$1.apply(PairRDDFunctions.scala:505)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$groupByKey$1.apply(PairRDDFunctions.scala:498)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
        at org.apache.spark.rdd.PairRDDFunctions.groupByKey(PairRDDFunctions.scala:498)
        at org.apache.spark.rdd.RDD$$anonfun$groupBy$3.apply(RDD.scala:722)
        at org.apache.spark.rdd.RDD$$anonfun$groupBy$3.apply(RDD.scala:720)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
        at org.apache.spark.rdd.RDD.groupBy(RDD.scala:720)
        at org.apache.spark.rdd.RDD$$anonfun$groupBy$1.apply(RDD.scala:692)
        at org.apache.spark.rdd.RDD$$anonfun$groupBy$1.apply(RDD.scala:692)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
        at org.apache.spark.rdd.RDD.groupBy(RDD.scala:691)
        at org.apache.spark.api.java.JavaRDDLike$class.groupBy(JavaRDDLike.scala:243)
        at org.apache.spark.api.java.AbstractJavaRDDLike.groupBy(JavaRDDLike.scala:45)
        at zipkin2.dependencies.elasticsearch.ElasticsearchDependenciesJob.run(ElasticsearchDependenciesJob.java:182)
        at zipkin2.dependencies.elasticsearch.ElasticsearchDependenciesJob.run(ElasticsearchDependenciesJob.java:163)
        at zipkin2.dependencies.ZipkinDependenciesJob.main(ZipkinDependenciesJob.java:73)
```

openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

**Comment by adriancole** [comment]
sure.. we can look into this if spark 3 doesn't implicitly fix this via
scala version or something. thanks!

**Comment by shakuzen** [comment]
Looks like the shaded version of asm isn't one that supports Java 11. This would presumably be fixed in the 3.0 version of Spark.

**Comment by jorgheymans** [comment]
https://spark.apache.org/releases/spark-release-3-0-0.html it's out , i'll have a look to see what's involved in upgrading and what the benefits would be in terms of memory usage.

**Comment by jcchavezs** [comment]
<3

**Comment by jorgheymans** [comment]
So yeah no https://github.com/elastic/elasticsearch-hadoop/issues/1412 , until elasticsearch-spark can handle Scala 2.12 they cannot support spark 3.0 and we are stuck on 2.x.

**Comment by AceHack** [comment]
Any update on when this might be supported?

**Comment by jorgheymans** [comment]
See my previous comment, we're waiting on elasticsearch-spark for this.

**Comment by adriancole** [comment]
https://github.com/elastic/elasticsearch-hadoop/pull/1521 is the most recent development. Only elasticsearch is holding this back
