### ISSUE TITLE
Job fails with "IllegalArgumentException: Comparison method violates its general contract"

### ISSUE THREAD

**Issue by ccmtaylor** [openzipkin/zipkin-dependencies#125]
The spark job (on v2.0.4) aborts (after ~30m in our case) with the exception `IllegalArgumentException: Comparison method violates its general contract`, because `zipkin2.internal.Trace#CLEANUP_COMPARATOR` violates the `Comparator` contract.

Indeed, it is possible to construct two spans for which `s1.equals(s2) == (CLEANUP_COMPARATOR.compare(s1, s2) == 0)` doesn't hold:

```java
  // in the context of TraceTest.java
  @Test public void cleanupComparator_consistentWithEquals() {
    Span s1 = span("a", "a", "b", Kind.SERVER, "frontend", "1.2.3.5", true);
    Span s2 = s1.toBuilder()
      .remoteEndpoint(Endpoint.newBuilder()
        .serviceName("backend")
        .build()
      )
      .build();
    assertThat(s1.equals(s2)).isEqualTo(Trace.CLEANUP_COMPARATOR.compare(s1, s2) == 0);
  }
```

<details>
<summary>stdout logs</summary>
```
18/12/19 13:21:28 INFO CassandraDependenciesJob: Running Dependencies job for 2018-12-19: 1545177600000000 ≤ Span.timestamp 1545263999999999
18/12/19 13:21:28 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
18/12/19 13:21:29 WARN Java7Support: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
18/12/19 13:52:19 ERROR Executor: Exception in task 2697.0 in stage 0.0 (TID 2697)
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:899)
	at java.util.TimSort.mergeAt(TimSort.java:516)
	at java.util.TimSort.mergeForceCollapse(TimSort.java:457)
	at java.util.TimSort.sort(TimSort.java:254)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1462)
	at java.util.Collections.sort(Collections.java:175)
	at zipkin2.internal.Trace.merge(Trace.java:32)
	at zipkin2.internal.SpanNode$Builder.build(SpanNode.java:139)
	at zipkin2.internal.DependencyLinker.putTrace(DependencyLinker.java:57)
	at zipkin2.dependencies.cassandra3.SpansToDependencyLinks.call(SpansToDependencyLinks.java:54)
	at zipkin2.dependencies.cassandra3.CassandraRowsToDependencyLinks.call(CassandraRowsToDependencyLinks.java:50)
	at zipkin2.dependencies.cassandra3.CassandraRowsToDependencyLinks.call(CassandraRowsToDependencyLinks.java:25)
	at org.apache.spark.api.java.JavaPairRDD$$anonfun$fn$1$1.apply(JavaPairRDD.scala:678)
	at org.apache.spark.api.java.JavaPairRDD$$anonfun$fn$1$1.apply(JavaPairRDD.scala:678)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$flatMapValues$1$$anonfun$apply$39$$anonfun$apply$40.apply(PairRDDFunctions.scala:769)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$flatMapValues$1$$anonfun$apply$39$$anonfun$apply$40.apply(PairRDDFunctions.scala:768)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:191)
	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:62)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
</details>

**Comment by adriancole** [comment]
very interesting that spark snoops into sub-stage conversions!

**Comment by adriancole** [comment]
actually this is TimSort not spark
