### ISSUE TITLE
Fail to start job with Mysql Storage

### ISSUE THREAD

**Issue by pickmonster** [openzipkin/zipkin-dependencies#154]
Exception in thread "main" java.lang.UnsupportedOperationException
at shaded.com.google.common.collect.ImmutableMap.putAll(ImmutableMap.java:350)
at zipkin2.dependencies.mysql.MySQLDependenciesJob$Builder.conf(MySQLDependenciesJob.java:130)
at zipkin2.dependencies.ZipkinDependenciesJob.main(ZipkinDependenciesJob.java:80)

**Comment by pickmonster** [comment]
But I just use zipkin-dependencies latest version to start image in docker. I have not do anything else.

**Comment by anuraaga** [comment]
Hi - thanks for reporting! It was indeed a bug in the latest version. Can you try the `:master` tag to see if it fixes your issue? If so, we'll release a new version with the fix soon.

**Comment by anuraaga** [comment]
(sorry for automatically closing the issue from that PR without giving you more context!)

**Comment by anuraaga** [comment]
I have gone ahead and released 2.4.1 - please try it out and let us know if you see any more bugs. Thanks!
