### ISSUE TITLE
Zipkin dependencies fails with tls/ssl config

### ISSUE THREAD

**Issue by pankdhnd** [openzipkin/zipkin-dependencies#204]
## Describe the Bug
We are deploying zipkin and zipkin-dependencies in kubernetes env. We are using elasticsearch as storage and we see that indices are getting created in Zipkin for the trace data. We have made exactly same configuration for Zipkin and Zipkin dependencies for TLS, as both connect to a self managed elasticsearch instance.

We cofigured zipkin-dependencies with below env vars:
STORAGE_TYPe = elasticsearch
ES_HOSTS = elasticsearch clusterip service url and port
ES_INDEX = name of index
ES_USERNAME: elasticsearch username
ES_PASSWORD: elasticsearch password

We are passing JAVA_OPTS env variable with information of keystore, truststore, keystore password, truststore password etc. The JAVA_OPTS is exactly same in zipkin deployment and zipkin dependencies cronjob. But for the job pods, we keep getting error `Cannot initialize SSL - Invalid keystore format`.

We tried connection by skipping TLS/SSL verification, but unfortunately there is no such option available in dependencies \

Below is the full error text:

```
22/12/07 19:28:02 INFO ElasticsearchDependenciesJob: Processing spans from zipkin:span-2022-12-07/span
22/12/07 19:28:03 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot detect ES version - typically this happens if the network/Elasticsearch cluster is not accessible or when targeting a WAN/Cloud instance without the proper setting 'es.nodes.wan.only'
        at org.elasticsearch.hadoop.rest.InitializationUtils.discoverClusterInfo(InitializationUtils.java:348)
        at org.elasticsearch.hadoop.rest.RestService.findPartitions(RestService.java:220)
        at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions$lzycompute(AbstractEsRDD.scala:79)
        at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions(AbstractEsRDD.scala:78)
        at org.elasticsearch.spark.rdd.AbstractEsRDD.getPartitions(AbstractEsRDD.scala:48)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:273)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:269)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.rdd.RDD.partitions(RDD.scala:269)
        at org.apache.spark.Partitioner$$anonfun$4.apply(Partitioner.scala:78)
        at org.apache.spark.Partitioner$$anonfun$4.apply(Partitioner.scala:78)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.immutable.List.map(List.scala:296)
        at org.apache.spark.Partitioner$.defaultPartitioner(Partitioner.scala:78)
        at org.apache.spark.rdd.RDD$$anonfun$groupBy$1.apply(RDD.scala:714)
        at org.apache.spark.rdd.RDD$$anonfun$groupBy$1.apply(RDD.scala:714)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:385)
        at org.apache.spark.rdd.RDD.groupBy(RDD.scala:713)
        at org.apache.spark.api.java.JavaRDDLike$class.groupBy(JavaRDDLike.scala:243)
        at org.apache.spark.api.java.AbstractJavaRDDLike.groupBy(JavaRDDLike.scala:45)
        at zipkin2.dependencies.elasticsearch.ElasticsearchDependenciesJob.run(ElasticsearchDependenciesJob.java:189)
        at zipkin2.dependencies.elasticsearch.ElasticsearchDependenciesJob.run(ElasticsearchDependenciesJob.java:170)
        at zipkin2.dependencies.ZipkinDependenciesJob.main(ZipkinDependenciesJob.java:79)
Caused by: org.elasticsearch.hadoop.EsHadoopIllegalStateException: Cannot initialize SSL - Invalid keystore format
        at org.elasticsearch.hadoop.rest.commonshttp.SSLSocketFactory.createSSLContext(SSLSocketFactory.java:175)
        at org.elasticsearch.hadoop.rest.commonshttp.SSLSocketFactory.getSSLContext(SSLSocketFactory.java:160)
        at org.elasticsearch.hadoop.rest.commonshttp.SSLSocketFactory.createSocket(SSLSocketFactory.java:129)
        at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
        at org.elasticsearch.hadoop.rest.commonshttp.CommonsHttpTransport.doExecute(CommonsHttpTransport.java:685)
        at org.elasticsearch.hadoop.rest.commonshttp.CommonsHttpTransport.access$200(CommonsHttpTransport.java:73)
        at org.elasticsearch.hadoop.rest.commonshttp.CommonsHttpTransport$2.run(CommonsHttpTransport.java:659)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1692)
        at org.elasticsearch.hadoop.mr.security.HadoopUser.doAs(HadoopUser.java:66)
        at org.elasticsearch.hadoop.rest.commonshttp.CommonsHttpTransport.execute(CommonsHttpTransport.java:656)
        at org.elasticsearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:116)
        at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:432)
        at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:428)
        at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:388)
        at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:392)
        at org.elasticsearch.hadoop.rest.RestClient.get(RestClient.java:168)
        at org.elasticsearch.hadoop.rest.RestClient.mainInfo(RestClient.java:745)
        at org.elasticsearch.hadoop.rest.InitializationUtils.discoverClusterInfo(InitializationUtils.java:338)
        ... 27 more
Caused by: java.io.IOException: Invalid keystore format
        at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:666)
        at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:57)
        at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
        at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:71)
        at java.security.KeyStore.load(KeyStore.java:1445)
        at org.elasticsearch.hadoop.rest.commonshttp.SSLSocketFactory.loadKeyStore(SSLSocketFactory.java:200)
        at org.elasticsearch.hadoop.rest.commonshttp.SSLSocketFactory.loadKeyManagers(SSLSocketFactory.java:215)
        at org.elasticsearch.hadoop.rest.commonshttp.SSLSocketFactory.createSSLContext(SSLSocketFactory.java:173)
        ... 50 more
```

## Steps to Reproduce
1. Deploy zipkin and zipkin-dependencies pods in kubernetes env with elasticsearch storage and with TLS config
2. Push some traces to zipkin
3. Check dependencies graph

## Expected Behaviour
Dependencies page in zipkin should so the dependency graph for the traces

## Actual behaviour:
Cornjobs fails with Invalid keystore format error

**Comment by codefromthecrypt** [comment]
The elasticsearch code in zipkin-dependencies is from https://github.com/elastic/elasticsearch-hadoop and we pass the system property like so:

```
      sparkProperties.put(
          "es.net.ssl.keystore.location",
          getSystemPropertyAsFileResource("javax.net.ssl.keyStore"));
      sparkProperties.put(
          "es.net.ssl.keystore.pass", System.getProperty("javax.net.ssl.keyStorePassword", ""));
      sparkProperties.put(
          "es.net.ssl.truststore.location",
          getSystemPropertyAsFileResource("javax.net.ssl.trustStore"));
      sparkProperties.put(
          "es.net.ssl.truststore.pass", System.getProperty("javax.net.ssl.trustStorePassword", ""));
```

maybe you can make an extended docker-compose file that adds the properties so that it is easier to verify something is wrong?

https://github.com/openzipkin/zipkin-dependencies/tree/master/docker/examples

Also note that the code underneath is upgraded since you last opened this. Since you are getting invalid keystore errors, I suspect you are getting the properties through, just there is some discrepency in the format that ES accepted in the version of elasticsearch-hadoop was using at the time.

As it has been over a year, I'm closing this, but you can re-open if still interested in debugging.
