### ISSUE TITLE
failed to run zipkin-dependencies - module java.base does not "opens java.io" to unnamed module

### ISSUE THREAD

**Issue by selagnsknox** [openzipkin/zipkin-dependencies#206]
I'm running zipkin version 2.6.4 with Elasticsearch version 7.17.10. this work fine.
When I'm trying to run zipkin-dependencies version 2.6.4 in order to see dependencies in the UI Im getting the following error:

`23/05/10 18:26:34 DEBUG ElasticsearchDependenciesJob: Spark conf properties: spark.ui.enabled=false
23/05/10 18:26:34 DEBUG ElasticsearchDependenciesJob: Spark conf properties: es.index.read.missing.as.empty=true
23/05/10 18:26:34 DEBUG ElasticsearchDependenciesJob: Spark conf properties: es.nodes.wan.only=false
23/05/10 18:26:34 DEBUG ElasticsearchDependenciesJob: Spark conf properties: es.net.ssl.keystore.location=
23/05/10 18:26:34 DEBUG ElasticsearchDependenciesJob: Spark conf properties: es.net.ssl.keystore.pass=
23/05/10 18:26:34 DEBUG ElasticsearchDependenciesJob: Spark conf properties: es.net.ssl.truststore.location=
23/05/10 18:26:34 DEBUG ElasticsearchDependenciesJob: Spark conf properties: es.net.ssl.truststore.pass=
23/05/10 18:26:34 INFO ElasticsearchDependenciesJob: Processing spans from zipkin:span-2023-05-10/span
23/05/10 18:26:34 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.elasticsearch.hadoop.util.Version.<clinit>(Version.java:66)
        at org.elasticsearch.hadoop.rest.RestService.findPartitions(RestService.java:216)
        at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions$lzycompute(AbstractEsRDD.scala:79)
        at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions(AbstractEsRDD.scala:78)
        at org.elasticsearch.spark.rdd.AbstractEsRDD.getPartitions(AbstractEsRDD.scala:48)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:273)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:269)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.rdd.RDD.partitions(RDD.scala:269)
        at org.apache.spark.Partitioner$$anonfun$4.apply(Partitioner.scala:78)
        at org.apache.spark.Partitioner$$anonfun$4.apply(Partitioner.scala:78)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.immutable.List.map(List.scala:296)
        at org.apache.spark.Partitioner$.defaultPartitioner(Partitioner.scala:78)
        at org.apache.spark.rdd.RDD$$anonfun$groupBy$1.apply(RDD.scala:714)
        at org.apache.spark.rdd.RDD$$anonfun$groupBy$1.apply(RDD.scala:714)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:385)
        at org.apache.spark.rdd.RDD.groupBy(RDD.scala:713)
        at org.apache.spark.api.java.JavaRDDLike$class.groupBy(JavaRDDLike.scala:243)
        at org.apache.spark.api.java.AbstractJavaRDDLike.groupBy(JavaRDDLike.scala:45)
        at zipkin2.dependencies.elasticsearch.ElasticsearchDependenciesJob.run(ElasticsearchDependenciesJob.java:189)
        at zipkin2.dependencies.elasticsearch.ElasticsearchDependenciesJob.run(ElasticsearchDependenciesJob.java:170)
        at zipkin2.dependencies.ZipkinDependenciesJob.main(ZipkinDependenciesJob.java:79)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field protected byte[] java.io.ByteArrayInputStream.buf accessible: module java.base does not "opens java.io" to unnamed module @1c0dc10
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at org.elasticsearch.hadoop.util.ReflectionUtils.makeAccessible(ReflectionUtils.java:70)
        at org.elasticsearch.hadoop.util.IOUtils.<clinit>(IOUtils.java:53)
        ... 28 more
`

am I missing something? the elastic version is unsupported? I need to install something in order the run zipkin-dependencies?

**Comment by badygin-yakov** [comment]
Hi! I think you should downgrade jdk version to 1.8.

`Due to [SPARK-26134](https://issues.apache.org/jira/browse/SPARK-26134), Zipkin Dependencies currently requires Java 1.8 or 9 to run.`

https://github.com/openzipkin/zipkin-dependencies#quick-start

**Comment by selagnsknox** [comment]
@badygin-yakov 
thanks! 
when I downgrade my jdk to 1.8 it work
