### ISSUE TITLE
Zipkin dependency job fails for any malformed span

### ISSUE THREAD

**Issue by deepakmore1** [openzipkin/zipkin-dependencies#46]
Zipkin dependency job (spark job) fails when length of span is more than 10k bytes. 

1. Malformed span details should be logged. 
2. If this error can be ignored then job should proceed further.

`05:33:23.556 [task-result-getter-0] WARN  o.a.spark.scheduler.TaskSetManager - Lost task 0.0 in stage 0.0 (TID 0, localhost): java.lang.IllegalArgumentException: Malformed reading Span from TBinary:
        at zipkin.internal.ThriftCodec.exceptionReading(ThriftCodec.java:507)
        at zipkin.internal.ThriftCodec.read(ThriftCodec.java:444)
        at zipkin.internal.ThriftCodec.readSpan(ThriftCodec.java:69)
        at zipkin.dependencies.cassandra.CassandraDependenciesJob.toLinks(CassandraDependenciesJob.java:146)
        at zipkin.dependencies.cassandra.CassandraDependenciesJob.lambda$run$ef192ee8$1(CassandraDependenciesJob.java:131)
        at zipkin.dependencies.cassandra.CassandraDependenciesJob$$Lambda$4.call(Unknown Source)
        at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$1$1.apply(JavaRDDLike.scala:129)
        at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$1$1.apply(JavaRDDLike.scala:129)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:396)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:369)
        at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:189)
        at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:64)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: 13610 > 10000: possibly malformed thrift
        at zipkin.internal.ThriftCodec.guardLength(ThriftCodec.java:602)
        at zipkin.internal.ThriftCodec.readList(ThriftCodec.java:461)
        at zipkin.internal.ThriftCodec$ListAdapter.read(ThriftCodec.java:488)
        at zipkin.internal.ThriftCodec$ListAdapter.read(ThriftCodec.java:479)
        at zipkin.internal.ThriftCodec$4.read(ThriftCodec.java:291)
        at zipkin.internal.ThriftCodec$4.read(ThriftCodec.java:261)
        at zipkin.internal.ThriftCodec.read(ThriftCodec.java:442)
        ... 17 more`

**Comment by adriancole** [comment]
since `ThriftCodec.readList` is in the stack trace, it looks like you have a list of 13610 annotations or binary annotations in one span (or it is malformed).
