### ISSUE TITLE
dependency tab not showing all the services

### ISSUE THREAD

**Issue by tal-ni** [openzipkin/zipkin-dependencies#53]
I'm using MySql as the database layer and i have many traces coming from different services what are the steps I need to follow in order to see dependencies graph? 
I see only **one** service and no dependency graph between the services. 

Here an example:   
![image](https://cloud.githubusercontent.com/assets/17848026/19771662/5a6def20-9c6c-11e6-8ed4-030bf2392dc9.png)

**Comment by adriancole** [comment]
How are you instrumenting your services? If you are using normal zipkin
instrumentation, the key is making sure the service name reported by each
node is different. If you paste the JSON of one of your traces (wrapped in
```), it should be easy to tell why there's only one node.

**Comment by tal-ni** [comment]
I have also looked at the logs of the dependencies-job  and i see the following error:

org.apache.spark.**SparkException**: Could not find **HeartbeatReceiver** or it has been stopped.
	at org.apache.spark.rpc.netty.Dispatcher.postMessage(Dispatcher.scala:161)
	at org.apache.spark.rpc.netty.Dispatcher.postLocalMessage(Dispatcher.scala:126)
	at org.apache.spark.rpc.netty.NettyRpcEnv.ask(NettyRpcEnv.scala:227)
	at org.apache.spark.rpc.netty.NettyRpcEndpointRef.ask(NettyRpcEnv.scala:511)
	at org.apache.spark.rpc.RpcEndpointRef.askWithRetry(RpcEndpointRef.scala:100)
	at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$reportHeartBeat(Executor.scala:476)
	at org.apache.spark.executor.Executor$$anon$1$$anonfun$run$1.apply$mcV$sp(Executor.scala:505)
	at org.apache.spark.executor.Executor$$anon$1$$anonfun$run$1.apply(Executor.scala:505)
	at org.apache.spark.executor.Executor$$anon$1$$anonfun$run$1.apply(Executor.scala:505)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1801)
	at org.apache.spark.executor.Executor$$anon$1.run(Executor.scala:505)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by tal-ni** [comment]
I'm sending an example of the json . 
here it is:

```
[
  {
    "traceId": "8f584da7710cf3a1",
    "id": "8f584da7710cf3a1",
    "name": "get",
    "timestamp": 1478012981926000,
    "duration": 670000,
    "annotations": [
      {
        "timestamp": 1478012981926000,
        "value": "sr",
        "endpoint": {
          "serviceName": "rapido",
          "ipv4": "192.168.140.56",
          "port": 6003
        }
      },
      {
        "timestamp": 1478012981936000,
        "value": "timing.getEntitiesByContext.start",
        "endpoint": {
          "serviceName": "rapido",
          "ipv4": "192.168.140.56",
          "port": 6003
        }
      },
      {
        "timestamp": 1478012981943000,
        "value": "timing.getEntitiesByContext.end",
        "endpoint": {
          "serviceName": "rapido",
          "ipv4": "192.168.140.56",
          "port": 6003
        }
      },
      {
        "timestamp": 1478012981954000,
        "value": "timing.getEntitiesSecondTier.start",
        "endpoint": {
          "serviceName": "rapido",
          "ipv4": "192.168.140.56",
          "port": 6003
        }
      },
      {
        "timestamp": 1478012981966000,
        "value": "timing.getEntitiesSecondTier.end",
        "endpoint": {
          "serviceName": "rapido",
          "ipv4": "192.168.140.56",
          "port": 6003
        }
      },
      {
        "timestamp": 1478012981966000,
        "value": "timing.validateRouteParams.end",
        "endpoint": {
          "serviceName": "rapido",
          "ipv4": "192.168.140.56",
          "port": 6003
        }
      },
      {
        "timestamp": 1478012981966000,
        "value": "timing.validateRouteParams.start",
        "endpoint": {
          "serviceName": "rapido",
          "ipv4": "192.168.140.56",
          "port": 6003
        }
      },
      {
        "timestamp": 1478012982596000,
        "value": "ss",
        "endpoint": {
          "serviceName": "rapido",
          "ipv4": "192.168.140.56",
          "port": 6003
        }
      }
    ],
    "binaryAnnotations": [
      {
        "key": "http.status_code",
        "value": "200",
        "endpoint": {
          "serviceName": "rapido",
          "ipv4": "192.168.140.56",
          "port": 6003
        }
      },
      {
        "key": "http.url",
        "value": "http://rapido.corp.naturalint.com/v1/learn-more",
        "endpoint": {
          "serviceName": "rapido",
          "ipv4": "192.168.140.56",
          "port": 6003
        }
      }
    ]
  },
  {
    "traceId": "8f584da7710cf3a1",
    "id": "ab0d22488ffa71c5",
    "name": "get",
    "parentId": "8f584da7710cf3a1",
    "timestamp": 1478012981982000,
    "duration": 70000,
    "annotations": [
      {
        "timestamp": 1478012981982000,
        "value": "sr",
        "endpoint": {
          "serviceName": "locator-service",
          "ipv4": "192.168.140.56",
          "port": 6020
        }
      },
      {
        "timestamp": 1478012982052000,
        "value": "ss",
        "endpoint": {
          "serviceName": "locator-service",
          "ipv4": "192.168.140.56",
          "port": 6020
        }
      }
    ],
    "binaryAnnotations": [
      {
        "key": "http.status_code",
        "value": "200",
        "endpoint": {
          "serviceName": "locator-service",
          "ipv4": "192.168.140.56",
          "port": 6020
        }
      },
      {
        "key": "http.url",
        "value": "http://locator-service.corp.naturalint.com/api/v1/user-context?ip=undefined&useragent=Mozilla/5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_12_1)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/54.0.2840.71%20Safari/537.36",
        "endpoint": {
          "serviceName": "locator-service",
          "ipv4": "192.168.140.56",
          "port": 6020
        }
      }
    ]
  },
  {
    "traceId": "8f584da7710cf3a1",
    "id": "76ff0f273c5e17d4",
    "name": "get",
    "parentId": "8f584da7710cf3a1",
    "timestamp": 1478012982074000,
    "duration": 429000,
    "annotations": [
      {
        "timestamp": 1478012982074000,
        "value": "sr",
        "endpoint": {
          "serviceName": "article-rts",
          "ipv4": "192.168.140.56",
          "port": 6006
        }
      },
      {
        "timestamp": 1478012982503000,
        "value": "ss",
        "endpoint": {
          "serviceName": "article-rts",
          "ipv4": "192.168.140.56",
          "port": 6006
        }
      }
    ],
    "binaryAnnotations": [
      {
        "key": "http.status_code",
        "value": "200",
        "endpoint": {
          "serviceName": "article-rts",
          "ipv4": "192.168.140.56",
          "port": 6006
        }
      },
      {
        "key": "http.url",
        "value": "http://article-rts.corp.naturalint.com/component/aggregated/579df695095b7dfd579b46e8?pageType_id=579df61842ce561971cf2ed1&pageType_name=articles&page_type_ver_id=579df61842ce561971cf2ee3&vertical_id=579df685095b7dfd579b46e0&vertical_name=v1&vertical_ver_id=57d67007f7930eb35d31c72d&segment_id=579df695095b7dfd579b46e8&segment_name=default&segment_ver_id=57ffdb90c030c50e2d5adfe2&c=null&utm_source=null&refdomain=com&pl_ver_id=57d5768e9c89cdc3288f8cf4&pl_id=57d5768e9c89cdc3288f8cf2&pl_var_id=57d5768e9c89cdc3288f8cf1&themeName=mindup&layoutName=articles&layoutVariantName=default&umb_site_id=579df61787e5f83534be1f2d&site_id=248&lang=en&rapido%5Bhost%5D=rapido.corp.naturalint.com&rapido%5Bpath%5D=%2Fv1%2Flearn-more&",
        "endpoint": {
          "serviceName": "article-rts",
          "ipv4": "192.168.140.56",
          "port": 6006
        }
      }
    ]
  }
]

```

Thanks Adrian.

**Comment by jorgheymans** [comment]
Verifying this old v1 trace against Lens, everything still shows up as expected which in itself is really amazing and a testament to the work that has gone into keeping this stuff backwards compatible :1st_place_medal: 

![image](https://user-images.githubusercontent.com/193792/80723210-a43ddd00-8b00-11ea-9c45-83a1033029a7.png)
