### ISSUE TITLE
Issue with Spark/Cassandra/commons-codecs

### ISSUE THREAD

**Issue by ys** [openzipkin/zipkin-dependencies#68]
When using zipkin-dependencies against a non local spark cluster, I get

```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Base64.encodeBase64String([B)Ljava/lang/String;
	at com.datastax.spark.connector.cql.CassandraConnectorConf.serializedConfString$lzycompute(CassandraConnectorConf.scala:42)
...
at zipkin.dependencies.cassandra.CassandraDependenciesJob.run(CassandraDependenciesJob.java:149)
	at zipkin.dependencies.ZipkinDependenciesJob.main(ZipkinDependenciesJob.java:48)
```
<details>
 <summary>
Full trace
</summary>

```

Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Base64.encodeBase64String([B)Ljava/lang/String;
	at com.datastax.spark.connector.cql.CassandraConnectorConf.serializedConfString$lzycompute(CassandraConnectorConf.scala:42)
	at com.datastax.spark.connector.cql.CassandraConnectorConf.serializedConfString(CassandraConnectorConf.scala:37)
	at com.datastax.spark.connector.cql.CassandraConnectorConf.hashCode(CassandraConnectorConf.scala:45)
	at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:210)
	at scala.collection.concurrent.TrieMap$MangledHashing.hash(TrieMap.scala:916)
	at scala.collection.concurrent.TrieMap.computeHash(TrieMap.scala:826)
	at scala.collection.concurrent.TrieMap.get(TrieMap.scala:841)
	at com.datastax.spark.connector.cql.RefCountedCache.acquire(RefCountedCache.scala:50)
	at com.datastax.spark.connector.cql.CassandraConnector.openSession(CassandraConnector.scala:80)
	at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:107)
	at com.datastax.spark.connector.cql.CassandraConnector.withClusterDo(CassandraConnector.scala:118)
	at com.datastax.spark.connector.cql.Schema$.fromCassandra(Schema.scala:330)
	at com.datastax.spark.connector.cql.Schema$.tableFromCassandra(Schema.scala:350)
	at com.datastax.spark.connector.rdd.CassandraTableRowReaderProvider$class.tableDef(CassandraTableRowReaderProvider.scala:50)
	at com.datastax.spark.connector.rdd.CassandraTableScanRDD.tableDef$lzycompute(CassandraTableScanRDD.scala:60)
	at com.datastax.spark.connector.rdd.CassandraTableScanRDD.tableDef(CassandraTableScanRDD.scala:60)
	at com.datastax.spark.connector.rdd.CassandraTableRowReaderProvider$class.verify(CassandraTableRowReaderProvider.scala:137)
	at com.datastax.spark.connector.rdd.CassandraTableScanRDD.verify(CassandraTableScanRDD.scala:60)
	at com.datastax.spark.connector.rdd.CassandraTableScanRDD.getPartitions(CassandraTableScanRDD.scala:230)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at com.datastax.spark.connector.rdd.SpannedRDD.getPartitions(SpannedRDD.scala:25)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.Partitioner$.defaultPartitioner(Partitioner.scala:65)
	at org.apache.spark.api.java.JavaPairRDD.reduceByKey(JavaPairRDD.scala:526)
	at zipkin.dependencies.cassandra.CassandraDependenciesJob.run(CassandraDependenciesJob.java:149)
	at zipkin.dependencies.ZipkinDependenciesJob.main(ZipkinDependenciesJob.java:48)
```
</details>
I have no idea what is happening there. Sounds like some conflicts between projects maybe:(

Any idea?

**Comment by ys** [comment]
Adding commons-codec 1.10 to main pom.xml fixed the issue.

**Comment by ys** [comment]
Unsure if it needs to be there or on the cassandra one.

**Comment by JodeZer** [comment]
We encountered  the same problem. Hope useful solution can be merged!   
:)

**Comment by ys** [comment]
Yeah I have a simple fix in #70 but I don't know the implications as I am not an expert in Java:D

**Comment by NithinMadhavanpillai** [comment]
@adriancole @ys . 
we encountered the same problem. 
our tempory solution was : 
1 ) Added this dependency 
    <dependency>
      <groupId>commons-codec</groupId>
      <artifactId>commons-codec</artifactId>
      <version>1.10</version>
    </dependency>
2)  mvn clean install 
3) created a new docker file 
           FROM openzipkin/zipkin-dependencies
           RUN mv /zipkin-dependencies/zipkin-dependencies.jar /zipkin-dependencies/test.jar
          COPY zipkin-dependencies.jar  /zipkin-dependencies/
job started working . 

Hopefully this fix gets merged and we dont need to have this interim docker file .

**Comment by adriancole** [comment]
thanks for the work, folks. I can take a look at this now back from holiday

**Comment by adriancole** [comment]
1.6.0 on the way out. thanks!

**Comment by adriancole** [comment]
@ys mind checking this?

**Comment by ys** [comment]
I will test that today.

**Comment by ys** [comment]
Works great for us, thanks!
