### ISSUE TITLE
Set minimum version to spark 2.2 (scala 2.11 hadoop 2.7+)

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-dependencies#77]
Many people use zipkin-dependencies as a "dumb cron job" to create the service graph in zipkin. Some have no idea spark is inside. We formerly pinned to an old version of spark, but that reason (old hadoop install) seems to have disappeared. Meanwhile the old version of dependencies fire security alarm bells (#76)

Unless we hear otherwise in a week, we'll update to the most current dependencies and cut a release with them.

**Comment by adriancole** [comment]
https://github.com/openzipkin/zipkin-dependencies/pull/78 can't go 2.2 yet due to cassandra

**Comment by ys** [comment]
I am getting errors due to this... 
I have now a 2.1 spark cluster but have error about not finding Cluster datastax class now... 

Any idea what that could be?

**Comment by adriancole** [comment]
@ys I will start a local 2.1 cluster and see if I can reproduce it

**Comment by ys** [comment]
Thanks!

<details>
<summary>The stacktrace</summary>
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 3 in stage 0.0 failed 4 times, most recent failure: Lost task 3.3 in stage 0.0 (TID 15, 10.0.136.155, executor 0): java.lang.NoClassDefFoundError: Could not initialize class com.datastax.driver.core.Cluster
	at com.datastax.spark.connector.cql.DefaultConnectionFactory$.clusterBuilder(CassandraConnectionFactory.scala:43)
	at com.datastax.spark.connector.cql.DefaultConnectionFactory$.createCluster(CassandraConnectionFactory.scala:131)
	at com.datastax.spark.connector.cql.CassandraConnector$.com$datastax$spark$connector$cql$CassandraConnector$$createSession(CassandraConnector.scala:159)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$8.apply(CassandraConnector.scala:154)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$8.apply(CassandraConnector.scala:154)
	at com.datastax.spark.connector.cql.RefCountedCache.createNewValueAndKeys(RefCountedCache.scala:32)
	at com.datastax.spark.connector.cql.RefCountedCache.syncAcquire(RefCountedCache.scala:69)
	at com.datastax.spark.connector.cql.RefCountedCache.acquire(RefCountedCache.scala:57)
	at com.datastax.spark.connector.cql.CassandraConnector.openSession(CassandraConnector.scala:79)
	at com.datastax.spark.connector.cql.DefaultScanner.<init>(Scanner.scala:27)
	at com.datastax.spark.connector.cql.CassandraConnectionFactory$class.getScanner(CassandraConnectionFactory.scala:30)
	at com.datastax.spark.connector.cql.DefaultConnectionFactory$.getScanner(CassandraConnectionFactory.scala:35)
	at com.datastax.spark.connector.rdd.CassandraTableScanRDD.compute(CassandraTableScanRDD.scala:361)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at com.datastax.spark.connector.rdd.SpannedRDD.compute(SpannedRDD.scala:29)
	at com.datastax.spark.connector.rdd.SpannedRDD.compute(SpannedRDD.scala:22)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1435)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1423)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1422)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1422)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:802)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1650)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1605)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1594)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:628)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1925)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1938)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1951)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1965)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:936)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:935)
	at org.apache.spark.api.java.JavaRDDLike$class.collect(JavaRDDLike.scala:361)
	at org.apache.spark.api.java.AbstractJavaRDDLike.collect(JavaRDDLike.scala:45)
	at zipkin.dependencies.cassandra.CassandraDependenciesJob.run(CassandraDependenciesJob.java:171)
	at zipkin.dependencies.ZipkinDependenciesJob.main(ZipkinDependenciesJob.java:48)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.datastax.driver.core.Cluster
	at com.datastax.spark.connector.cql.DefaultConnectionFactory$.clusterBuilder(CassandraConnectionFactory.scala:43)
	at com.datastax.spark.connector.cql.DefaultConnectionFactory$.createCluster(CassandraConnectionFactory.scala:131)
	at com.datastax.spark.connector.cql.CassandraConnector$.com$datastax$spark$connector$cql$CassandraConnector$$createSession(CassandraConnector.scala:159)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$8.apply(CassandraConnector.scala:154)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$8.apply(CassandraConnector.scala:154)
	at com.datastax.spark.connector.cql.RefCountedCache.createNewValueAndKeys(RefCountedCache.scala:32)
	at com.datastax.spark.connector.cql.RefCountedCache.syncAcquire(RefCountedCache.scala:69)
	at com.datastax.spark.connector.cql.RefCountedCache.acquire(RefCountedCache.scala:57)
	at com.datastax.spark.connector.cql.CassandraConnector.openSession(CassandraConnector.scala:79)
	at com.datastax.spark.connector.cql.DefaultScanner.<init>(Scanner.scala:27)
	at com.datastax.spark.connector.cql.CassandraConnectionFactory$class.getScanner(CassandraConnectionFactory.scala:30)
	at com.datastax.spark.connector.cql.DefaultConnectionFactory$.getScanner(CassandraConnectionFactory.scala:35)
	at com.datastax.spark.connector.rdd.CassandraTableScanRDD.compute(CassandraTableScanRDD.scala:361)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at com.datastax.spark.connector.rdd.SpannedRDD.compute(SpannedRDD.scala:29)
	at com.datastax.spark.connector.rdd.SpannedRDD.compute(SpannedRDD.scala:22)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
</details>

**Comment by adriancole** [comment]
reproduced!

start spark
```bash
$ curl -s https://www-us.apache.org/dist/spark/spark-2.1.1/spark-2.1.1-bin-hadoop2.7.tgz|tar -xzf -
$ cd spark-2.1.1-bin-hadoop2.7/
$ ./sbin/start-master.sh; ./sbin/start-slave.sh spark://acole:7077
```

start dependencies against it
```bash
$ STORAGE_TYPE=cassandra SPARK_MASTER=spark://acole:7077 java -jar ./main/target/zipkin-dependencies*.jar
17/08/09 16:32:03 INFO CassandraRowsToDependencyLinks: Running Dependencies job for 2017-08-09: 1502236800000000 ≤ Span.timestamp 1502323199999999
17/08/09 16:32:03 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/08/09 16:32:04 WARN Utils: Your hostname, acole resolves to a loopback address: 127.0.0.1; using 192.168.1.10 instead (on interface en0)
17/08/09 16:32:04 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
17/08/09 16:32:04 WARN Java7Support: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
17/08/09 16:32:05 WARN NettyUtil: Found Netty's native epoll transport, but not running on linux-based operating system. Using NIO instead.
[Stage 0:>                                                          (0 + 6) / 6]17/08/09 16:32:07 WARN TaskSetManager: Lost task 4.0 in stage 0.0 (TID 4, 192.168.1.10, executor 0): java.lang.NoClassDefFoundError: Could not initialize class com.datastax.driver.core.Cluster
--snip--
```

**Comment by adriancole** [comment]
Strange thing is that this class is already included.. must be something indirect:

```java
$ jar -tvf zipkin-dependencies.jar |grep com.datastax.driver.core.Cluster
  1601 Tue Aug 08 09:34:12 MYT 2017 com/datastax/driver/core/Cluster$1.class
  2119 Tue Aug 08 09:34:12 MYT 2017 com/datastax/driver/core/Cluster$2.class
  3363 Tue Aug 08 09:34:12 MYT 2017 com/datastax/driver/core/Cluster$3.class
--snip--
```

**Comment by adriancole** [comment]
this is guava related https://issues.apache.org/jira/browse/SPARK-16725

**Comment by ys** [comment]
Ok, should we have a different version here? Or unshaded something something?

It is all voodoo to me:P

**Comment by adriancole** [comment]
sorry I am trying to work around this in the build

**Comment by ys** [comment]
Thanks so much for fixing this and I am happy it is not just us because that means we have bright minds able to help:)

**Comment by adriancole** [comment]
yeap. FWIW the next version of the cassandra driver will no longer depend on guava (too early for us now, but at least hacks can one day be removed)

**Comment by adriancole** [comment]
https://github.com/openzipkin/zipkin-dependencies/pull/86 should fix it. I'll release a quick patch once green

**Comment by ys** [comment]
Will test when back home and ping !

**Comment by adriancole** [comment]
thanks 1.8.1 should hopefully be synced when you are back
